language: cpp
sudo: false

script:
  #############################################################################
  # Conformance with Alpaka: Do not write __global__ CUDA kernels directly    #
  #############################################################################
  - test/hasCudaGlobalKeyword src/libPMacc
  - test/hasCudaGlobalKeyword src/picongpu
  - test/hasCudaGlobalKeyword examples

  #############################################################################
  # Disallow end-of-line (EOL) white spaces                                   #
  #############################################################################
  - test/hasEOLwhiteSpace

  #############################################################################
  # Disallow non-ASCII in source files and scripts                            #
  #############################################################################
  - test/hasNonASCII

  #############################################################################
  # Disallow spaces before pre-compiler macros                                #
  #############################################################################
  - test/hasSpaceBeforePrecompiler
